/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DateRangeSelect: typeof import('./src/components/DateRangeSelect.vue')['default']
    DateSelect: typeof import('./src/components/DateSelect.vue')['default']
    DatetimeSelect: typeof import('./src/components/DatetimeSelect.vue')['default']
    EnumSelect: typeof import('./src/components/EnumSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
